/**
 * Modernizer CLI — code analysis and doc sync.
 *
 * Usage:
 *   npm run modernizer:analyze        — Run code analysis, output JSON to stdout
 *   npm run modernizer:sync-docs      — Generate/update docs/api-endpoints.md
 */
import * as path from 'node:path';
import * as fs from 'node:fs';
import { analyzeProject } from '../../src/modules/modernizer/analyzeCore';

// ─── Doc Sync (CLI-only, not shared with NestJS module) ──────────

interface EndpointInfo {
  method: string;
  path: string;
  summary: string;
  controller: string;
}

const HTTP_DECORATORS: [RegExp, string][] = [
  [/@Get\s*\(\s*'([^']*)'\s*\)/, 'GET'],
  [/@Post\s*\(\s*'([^']*)'\s*\)/, 'POST'],
  [/@Put\s*\(\s*'([^']*)'\s*\)/, 'PUT'],
  [/@Patch\s*\(\s*'([^']*)'\s*\)/, 'PATCH'],
  [/@Delete\s*\(\s*'([^']*)'\s*\)/, 'DELETE'],
];

function generateDocs(projectRoot: string): string {
  const modulesDir = path.join(projectRoot, 'src', 'modules');

  if (!fs.existsSync(modulesDir)) {
    console.error(`Modules directory not found: ${modulesDir}`);
    return '# API Endpoints\n\nNo modules directory found.\n';
  }

  const endpoints = extractAllEndpoints(modulesDir);
  return renderMarkdown(endpoints);
}

function extractAllEndpoints(modulesDir: string): EndpointInfo[] {
  const endpoints: EndpointInfo[] = [];
  const entries = fs.readdirSync(modulesDir, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const controllerFiles = fs
      .readdirSync(path.join(modulesDir, entry.name))
      .filter((f: string) => f.endsWith('Controller.ts'));

    for (const cf of controllerFiles) {
      const filePath = path.join(modulesDir, entry.name, cf);
      const controllerEndpoints = parseController(filePath);
      endpoints.push(...controllerEndpoints);
    }
  }

  return endpoints.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

function parseController(filePath: string): EndpointInfo[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');

  const controllerMatch = content.match(/@Controller\s*\(\s*'([^']*)'\s*\)/);
  const prefix = controllerMatch ? `/${controllerMatch[1]}` : '';

  const classMatch = content.match(/export\s+class\s+(\w+Controller)/);
  const controllerName = classMatch ? classMatch[1] : 'Unknown';

  const endpoints: EndpointInfo[] = [];
  let currentSummary = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    const apiOpMatch = line.match(/@ApiOperation\s*\(\s*\{\s*summary:\s*'([^']*)'/);
    if (apiOpMatch) {
      currentSummary = apiOpMatch[1];
      continue;
    }

    for (const [regex, method] of HTTP_DECORATORS) {
      const match = regex.exec(line);
      if (match) {
        const routePath = match[1];
        const fullPath = `${prefix}${routePath ? `/${routePath}` : ''}`;

        endpoints.push({
          method,
          path: `/api/v1${fullPath}`,
          summary: currentSummary || `${method} ${fullPath}`,
          controller: controllerName,
        });

        currentSummary = '';
        break;
      }
    }

    if (
      !line.startsWith('@') &&
      !line.startsWith('//') &&
      !line.startsWith('*') &&
      line.length > 0
    ) {
      currentSummary = '';
    }
  }

  return endpoints;
}

function renderMarkdown(endpoints: EndpointInfo[]): string {
  const lines: string[] = [
    '# API Endpoints',
    '',
    `> Auto-generated by modernizer:sync-docs — ${new Date().toISOString().split('T')[0]}`,
    '',
    `**Total endpoints: ${endpoints.length}**`,
    '',
    '| Method | Path | Summary | Controller |',
    '|--------|------|---------|------------|',
  ];

  for (const ep of endpoints) {
    lines.push(`| ${ep.method} | \`${ep.path}\` | ${ep.summary} | ${ep.controller} |`);
  }

  return lines.join('\n') + '\n';
}

// ─── CLI Entry Point ─────────────────────────────────────────────

function main(): void {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === 'help' || command === '--help') {
    console.log(`
Usage:
  npm run modernizer:analyze       Run code analysis, output JSON to stdout
  npm run modernizer:sync-docs     Generate docs/api-endpoints.md
`);
    process.exit(0);
  }

  const root = path.resolve(__dirname, '..', '..');

  if (command === 'analyze') {
    const srcDir = path.join(root, 'src');
    const result = analyzeProject(srcDir);
    console.log(JSON.stringify(result, null, 2));

    if (result.summary.total > 0) {
      console.error(`\nFound ${result.summary.total} issue(s):`);
      for (const [cat, count] of Object.entries(result.summary.byCategory)) {
        console.error(`  ${cat}: ${count}`);
      }
    } else {
      console.error('\nNo issues found!');
    }
  } else if (command === 'sync-docs') {
    const markdown = generateDocs(root);
    const docsDir = path.join(root, '..', '..', 'docs');
    const outputPath = path.join(docsDir, 'api-endpoints.md');

    fs.mkdirSync(docsDir, { recursive: true });
    fs.writeFileSync(outputPath, markdown, 'utf-8');
    console.log(`Documentation generated at: ${outputPath}`);
  } else {
    console.error(`Unknown command: ${command}. Use 'analyze' or 'sync-docs'.`);
    process.exit(1);
  }
}

main();
