import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'node:fs';
import * as path from 'node:path';

interface EndpointInfo {
  method: string;
  path: string;
  summary: string;
  controller: string;
}

@Injectable()
export class DocSyncService {
  private readonly logger = new Logger(DocSyncService.name);

  private readonly HTTP_DECORATORS: [RegExp, string][] = [
    [/@Get\s*\(\s*'([^']*)'\s*\)/, 'GET'],
    [/@Post\s*\(\s*'([^']*)'\s*\)/, 'POST'],
    [/@Put\s*\(\s*'([^']*)'\s*\)/, 'PUT'],
    [/@Patch\s*\(\s*'([^']*)'\s*\)/, 'PATCH'],
    [/@Delete\s*\(\s*'([^']*)'\s*\)/, 'DELETE'],
  ];

  /**
   * Scan all controller files and generate a markdown endpoint table.
   */
  generateDocs(projectRoot?: string): string {
    const root = projectRoot ?? this.resolveProjectRoot();
    const srcDir = path.join(root, 'apps', 'coreApi', 'src');

    if (!fs.existsSync(srcDir)) {
      this.logger.warn(`Source directory not found: ${srcDir}`);
      return '# API Endpoints\n\nNo source directory found.\n';
    }

    const endpoints = this.extractAllEndpoints(srcDir);
    return this.renderMarkdown(endpoints);
  }

  private resolveProjectRoot(): string {
    return path.resolve(__dirname, '..', '..', '..', '..', '..');
  }

  private extractAllEndpoints(srcDir: string): EndpointInfo[] {
    const endpoints: EndpointInfo[] = [];
    const modulesDir = path.join(srcDir, 'modules');

    if (!fs.existsSync(modulesDir)) return endpoints;

    const entries = fs.readdirSync(modulesDir, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const controllerFiles = fs
        .readdirSync(path.join(modulesDir, entry.name))
        .filter((f) => f.endsWith('Controller.ts'));

      for (const cf of controllerFiles) {
        const filePath = path.join(modulesDir, entry.name, cf);
        const controllerEndpoints = this.parseController(filePath);
        endpoints.push(...controllerEndpoints);
      }
    }

    return endpoints.sort(
      (a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method)
    );
  }

  private parseController(filePath: string): EndpointInfo[] {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');

    // Extract controller prefix
    const controllerMatch = content.match(/@Controller\s*\(\s*'([^']*)'\s*\)/);
    const prefix = controllerMatch ? `/${controllerMatch[1]}` : '';

    // Extract controller class name for display
    const classMatch = content.match(/export\s+class\s+(\w+Controller)/);
    const controllerName = classMatch ? classMatch[1] : 'Unknown';

    const endpoints: EndpointInfo[] = [];
    let currentSummary = '';

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      // Capture @ApiOperation summary (appears before the HTTP decorator)
      const apiOpMatch = line.match(/@ApiOperation\s*\(\s*\{\s*summary:\s*'([^']*)'/);
      if (apiOpMatch) {
        currentSummary = apiOpMatch[1];
        continue;
      }

      // Check for HTTP method decorators
      for (const [regex, method] of this.HTTP_DECORATORS) {
        const match = regex.exec(line);
        if (match) {
          const routePath = match[1];
          const fullPath = `${prefix}${routePath ? `/${routePath}` : ''}`;

          endpoints.push({
            method,
            path: `/api/v1${fullPath}`,
            summary: currentSummary || `${method} ${fullPath}`,
            controller: controllerName,
          });

          currentSummary = '';
          break;
        }
      }

      // Reset summary if line is not related
      if (
        !line.startsWith('@') &&
        !line.startsWith('//') &&
        !line.startsWith('*') &&
        line.length > 0
      ) {
        currentSummary = '';
      }
    }

    return endpoints;
  }

  private renderMarkdown(endpoints: EndpointInfo[]): string {
    const lines: string[] = [
      '# API Endpoints',
      '',
      `> Auto-generated by modernizer:sync-docs — ${new Date().toISOString().split('T')[0]}`,
      '',
      `**Total endpoints: ${endpoints.length}**`,
      '',
      '| Method | Path | Summary | Controller |',
      '|--------|------|---------|------------|',
    ];

    for (const ep of endpoints) {
      lines.push(`| ${ep.method} | \`${ep.path}\` | ${ep.summary} | ${ep.controller} |`);
    }

    return lines.join('\n') + '\n';
  }
}
